### ISSUE TITLE
Update readme.md to reflect self mounting components

### ISSUE THREAD

**Issue by perkinsjr** [clerkinc/clerk-hasura-starter#3]
Hey all, I was just checking this out as I move an experimental app to Clerk with Hasura. 

I noticed the starter doesn't explain that you should be use self mounted components and should make changes in the dashboard. 

Between the docs and this starter, there is not a clear example of making a request to Hasura queries once you have an Apollo Wrapped in your Next app.

**Comment by nachoiacovino** [comment]
Hello, James, please tell us if #4 is what you were looking for or if we should add something else.

Thank you for opening the issue! 😁

**Comment by perkinsjr** [comment]
Look good to me, closing
