### ISSUE TITLE
Can't execute Apollo Graphql queries/mutations in the public routes 

### ISSUE THREAD

**Issue by venkata-penumatsa** [clerkinc/clerk-hasura-starter#6]
Hi Team,

I started using/exploring this repo and I see there is one issue. i.e. we cannot execute any GraphQl queries/mutations in the public routes and getting the below error

![image](https://user-images.githubusercontent.com/41994139/144713453-9db21f7a-7348-4f50-9938-d49dcf657dc2.png)

Upon looking further into it, I have noticed the below code in the app.js file is causing the issue. as `ApolloProviderWrapper` is inside the `SignedIn` controlled component. 

![image](https://user-images.githubusercontent.com/41994139/144713555-80f13f3e-6145-4060-972f-1247331932c5.png)

If I try to wrap `ApolloProviderWrapper` for the `SignedOut` controlled component, it is giving the below `userUser `hook error

![image](https://user-images.githubusercontent.com/41994139/144713859-9ecdc1ab-242b-4d63-a5d4-ea72345df226.png)

Is there a way to tweak or change the code which will allow executing apollo queries/mutations inside all the components ?

Thanks
Venk

**Comment by perkinsjr** [comment]
Closing stale issue.
